{"name": "Ошибка при авторизации с неверным логином и паролем", "status": "passed", "start": 1706555522148, "stop": 1706555522763, "uuid": "37e79e0f-f784-4225-878d-3b8922b18aac", "historyId": "7ac1311b194a9e37c2cf50f2e37e5e29", "testCaseId": "7ac1311b194a9e37c2cf50f2e37e5e29", "fullName": "tests.test_login_user.TestLoginUser#test_user_login_incorrect_login_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-R8S2KV9"}, {"name": "thread", "value": "6472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}