{"name": "Ошибка при создании пользователя с данными уже зарегистрированного пользователя ", "status": "passed", "start": 1706555511828, "stop": 1706555512355, "uuid": "976e5c2b-ec8b-4c45-8f7e-c11c89121604", "historyId": "0d438a4d2f73fd339445316d7a909c3b", "testCaseId": "0d438a4d2f73fd339445316d7a909c3b", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_duplicate_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-R8S2KV9"}, {"name": "thread", "value": "6472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}